name: PR Title Check
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - release
jobs:
  merge_pr:
      uses: MangeshBangaleOrg/Test/.github/workflows/merge_pr.yml@workflow
      secrets: inherit
